# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LineamentExtractor
                                 A QGIS plugin
 dummy description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-14
        copyright            : (C) 2026 by dummy
        email                : dummy@localhost
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'dummy'
__date__ = '2026-05-14'
__copyright__ = '(C) 2026 by dummy'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LineamentExtractor class from file LineamentExtractor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lineament_extractor import LineamentExtractorPlugin
    return LineamentExtractorPlugin()
