# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LineamentExtractor
                                 A QGIS plugin
 dummy description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-14
        copyright            : (C) 2026 by dummy
        email                : dummy@localhost
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'dummy'
__date__ = '2026-05-14'
__copyright__ = '(C) 2026 by dummy'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from pathlib import Path
from qgis.core import (
    QgsProcessingException,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterFile,
    QgsProcessingParameterRasterDestination
)

# from PyQt5.QtGui import QColor

from . import BaseAlgorithm



class ApplyModel(BaseAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    NAME_ID = 'Apply DL Model'

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    DEM_INPUT = 'DEM_INPUT'
    MODEL_INPUT = 'MODEL_INPUT'
    LINEAMENT_OUTPUT = 'LINEAMENT_OUTPUT'


    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.DEM_INPUT,
                self.tr('Input training DEM layer'),
            )
        )

        self.addParameter(
            QgsProcessingParameterFile(
                self.MODEL_INPUT,
                self.tr('Input model file'),
                defaultValue=Path(__file__).resolve().parent.joinpath("rossi_et_al_2025.pth").as_posix(),
                # extension=".pth"
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.LINEAMENT_OUTPUT,
                self.tr('Output Lineament file'),
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        # self.addParameter(
        #     QgsProcessingParameterFeatureSink(
        #         self.OUTPUT,
        #         self.tr('Output layer')
        #     )
        # )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import torch
        import numpy
        from osgeo import gdal
        from qgis import processing

        from .lib import predict

        dem_input = self.parameterAsRasterLayer(parameters, self.DEM_INPUT, context)
        model_input = self.parameterAsFile(parameters, self.MODEL_INPUT, context)
        out_raster = self.parameterAsOutputLayer(parameters, self.LINEAMENT_OUTPUT, context)

        if not dem_input:
            raise QgsProcessingException("Invalid input raster layer.")

        if dem_input.bandCount() != 1:
            raise QgsProcessingException("Only for 1-band raster layers")

        # read as numpy
        dem_ds = gdal.Open(dem_input.dataProvider().dataSourceUri())
        in_dem = dem_ds.GetRasterBand(1).ReadAsArray()

        feedback.pushInfo(f'Raster lido com sucesso: {in_dem.shape}')

        in_dem = (in_dem - in_dem.min()) / (in_dem.max() - in_dem.min())
        in_dem = in_dem[:,:, numpy.newaxis]

        # Predict and save
        model = torch.load(model_input, weights_only=False)
        pred = predict(in_dem, model, tile_size=128, stride=32)

        out_driver = gdal.GetDriverByName('GTiff')
        dst_ds = out_driver.CreateCopy(out_raster, dem_ds, strict=0) #, options=["COMPRESS=LZW"])

        dst_band = dst_ds.GetRasterBand(1)
        dst_band.WriteArray(pred)

        # Converter para 8 bits
        # gdal_translate -ot Byte -of GTiff -co NBITS=1 /home/mota/vscode/Lineament_DEM_extractor/draft/SRTM_lineament_finder-main/SRTM_lineament_finder-main/lineamentos_predict.tif /tmp/processing_wWwnWC/cb95cfd8fa764a288dbd53b3a8a29d2c/OUTPUT.tif

        dst_band.FlushCache()

        # # Usar GRASS GIS para converter raster para vetor
        # # Primeiro anular os pixels 0
        # processing.run(
        #     "grass:r.null", 
        #     {
        #         'map':'/tmp/processing_wWwnWC/7341f9b98a36401cbe314c07bbfb939f/OUTPUT.tif',
        #         'setnull':'0',
        #         'null':None,
        #         '-f':False,
        #         '-i':False,
        #         '-n':False,
        #         '-c':False,
        #         '-r':False,
        #         'output':'TEMPORARY_OUTPUT',
        #         'GRASS_REGION_PARAMETER':None,
        #         'GRASS_REGION_CELLSIZE_PARAMETER':0,
        #         'GRASS_RASTER_FORMAT_OPT':'',
        #         'GRASS_RASTER_FORMAT_META':''
        #     }
        # )

        # # Afinar o vetor gerado
        # processing.run(
        #     "grass:r.thin", 
        #     {
        #         'input':'/tmp/processing_wWwnWC/31b33da529464d0bb6c217c29e00da38/output.tif',
        #         'iterations':200,
        #         'output':'TEMPORARY_OUTPUT',
        #         'GRASS_REGION_PARAMETER':None,
        #         'GRASS_REGION_CELLSIZE_PARAMETER':0,
        #         'GRASS_RASTER_FORMAT_OPT':'',
        #         'GRASS_RASTER_FORMAT_META':''
        #     }
        # )

        # # Vetorizar
        # processing.run(
        #     "grass:r.to.vect", 
        #     {
        #         'input':'/tmp/processing_wWwnWC/868e9138002044159f385fd861bab206/output.tif',
        #         'type':0,
        #         'column': 'value',
        #         '-s':False,
        #         '-v':False,
        #         '-z':False,
        #         '-b':False,
        #         '-t':True,
        #         'output':'TEMPORARY_OUTPUT',
        #         'GRASS_REGION_PARAMETER':None,
        #         'GRASS_REGION_CELLSIZE_PARAMETER':0,
        #         'GRASS_OUTPUT_TYPE_PARAMETER':0,
        #         'GRASS_VECTOR_DSCO':'',
        #         'GRASS_VECTOR_LCO':'',
        #         'GRASS_VECTOR_EXPORT_NOCAT':False
        #     }
        # )

        # # Generalizar

        # processing.run(
        #     "grass:v.generalize", 
        #     {
        #         'input':'/tmp/processing_wWwnWC/6339629456d445e1b1d2f525b2ca4404/output.gpkg',
        #         'type':[0,1,2],
        #         'cats':'',
        #         'where':'',
        #         'method':0,
        #         'threshold':1,
        #         'look_ahead':7,
        #         'reduction':50,
        #         'slide':0.5,
        #         'angle_thresh':3,
        #         'degree_thresh':0,
        #         'closeness_thresh':0,
        #         'betweeness_thresh':0,
        #         'alpha':1,
        #         'beta':1,
        #         'iterations':1,
        #         '-t':False,
        #         '-l':True,
        #         'output':'TEMPORARY_OUTPUT',
        #         'error':'TEMPORARY_OUTPUT',
        #         'GRASS_REGION_PARAMETER':None,
        #         'GRASS_SNAP_TOLERANCE_PARAMETER':-1,
        #         'GRASS_MIN_AREA_PARAMETER':0.0001,
        #         'GRASS_OUTPUT_TYPE_PARAMETER':0,
        #         'GRASS_VECTOR_DSCO':'',
        #         'GRASS_VECTOR_LCO':'',
        #         'GRASS_VECTOR_EXPORT_NOCAT':False
        #     }
        # )
    
        # 2. Run your underlying processing tool (e.g., native or GDAL algorithm)
        # Be sure to assign the output to the destination path
        # processing.run("native:some_raster_tool", {
        #     'INPUT': parameters['INPUT'],
        #     'OUTPUT': out_raster
        # }, context=context, feedback=feedback)
        
        # 3. Return the OUTPUT dictionary
        return {'OUTPUT': out_raster}
    
    # def postProcessAlgorithm(self, context, feedback):
    #     # 5. This method runs AFTER the processing steps finish
    #     # It handles the visual styling when the layer loads into QGIS
    #     outputs = self.getOutputs()
        
    #     if self.OUTPUT in outputs:
    #         # Load the newly created output layer from memory/context
    #         output_id = outputs[self.OUTPUT]
    #         output_layer = context.mapLayer(output_id)
            
    #         # if isinstance(output_layer, QgsRasterLayer):
    #         feedback.pushInfo("Applying discrete symbology to output layer...")
            
    #         # Apply raster symbology        
    #         shader = QgsColorRampShader()
    #         shader.setColorRampType(QgsColorRampShader.Discrete) # Sets to Discrete mode
    #         shader.setColorRampItemList([
    #             QgsColorRampShader.ColorRampItem(1, QColor(0, 0, 0), "Lineament"),
    #             QgsColorRampShader.ColorRampItem(0, QColor(255, 255, 0), "Absent")
    #         ])

    #         # 4. Create the raster shader object and the renderer
    #         raster_shader = QgsRasterShader()
    #         raster_shader.setRasterShaderFunction(shader)
            
    #         # Apply renderer to band 1
    #         renderer = QgsSingleBandPseudoColorRenderer(output_layer.dataProvider(), 1, raster_shader)
    #         output_layer.setRenderer(renderer)
            
    #         # Signal QGIS to update the Layer Panel Legend
    #         output_layer.triggerRepaint()
                
    #     return super().postProcessAlgorithm(context, feedback)

    def createInstance(self):
        return ApplyModel()
