"""
/***************************************************************************
 LineamentExtractor
                                 A QGIS plugin
 dummy description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-14
        copyright            : (C) 2026 by dummy
        email                : dummy@localhost
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'dummy'
__date__ = '2026-05-14'
__copyright__ = '(C) 2026 by dummy'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import (QgsProcessingException,
                       QgsProcessingParameterString,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterFolderDestination)

from . import BaseAlgorithm
from .device import get_device_details, identify_device


class GenerateModel(BaseAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    NAME_ID = 'Generate DL Model'

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    DEM_INPUT = 'DEM_INPUT'
    LINEAMENT_ANNOTATION = 'LINEAMENT_ANNOTATION'
    BATCH_SIZE = 'BATCH_SIZE'
    TILE_SIZE = 'TILE_SIZE'
    LEARNING_RATE = 'LEARNING_RATE'
    WEIGHT_DECAY = 'WEIGHT_DECAY'
    NUM_EPOCHS = 'NUM_EPOCHS'
    FIRST_HIDDEN_CHANNELS = 'FIRST_HIDDEN_CHANNELS'
    DEPTH = 'DEPTH'
    MODEL_NAME = 'MODEL_NAME'
    OUTPUT_DIR = 'OUTPUT_DIR'
    

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.DEM_INPUT,
                self.tr('Input training DEM layer'),
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.LINEAMENT_ANNOTATION,
                self.tr('Input training Lineament Annotation'),
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.BATCH_SIZE,        # Unique identifier
                self.tr('Batch size'),   # Label for users
                type=QgsProcessingParameterNumber.Integer, # Set as Integer
                defaultValue=32,            # Optional default
                minValue=1,                 # Optional minimum
                maxValue=100                # Optional maximum
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.TILE_SIZE,
                self.tr('Tile size'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=128,
                minValue=1,
                maxValue=1024
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.LEARNING_RATE,
                self.tr('Learning rate'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=0.0004,
                # minValue=1,
                # maxValue=1024
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.WEIGHT_DECAY,
                self.tr('Weight decay'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=1e-12,
                # minValue=1,
                # maxValue=1024
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.NUM_EPOCHS,
                self.tr('Number of epochs'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=50,
                minValue=1,
                maxValue=100
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.FIRST_HIDDEN_CHANNELS,
                self.tr('First hidden channels'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=16,
                minValue=1,
                maxValue=100
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.DEPTH,
                self.tr('Depth'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=5,
                minValue=1,
                maxValue=100
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.MODEL_NAME,
                self.tr('Model Name'),                  # Rótulo da Interface
                # fileFilter='PyTorch Models (*.pth)',   # Filtro de extensão obrigatório
                # defaultValue=None,
                # optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterFolderDestination(
                self.OUTPUT_DIR,
                self.tr('Output Folder'),                  # Rótulo da Interface
                # fileFilter='PyTorch Models (*.pth)',   # Filtro de extensão obrigatório
                # defaultValue=None,
                # optional=False
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import torch
        import numpy
        from osgeo import gdal

        from pathlib import Path

        from . import lib

        # Trabalha o DEM
        raster_layer = self.parameterAsRasterLayer(
            parameters,
            self.DEM_INPUT,
            context
        )

        if not raster_layer:
            raise QgsProcessingException("Invalid input raster layer.")

        if raster_layer.bandCount() != 1:
            raise QgsProcessingException("Only for 1-band raster layers")

        # Open the file with GDAL
        dem_ds = gdal.Open(raster_layer.dataProvider().dataSourceUri())
        in_dem = dem_ds.GetRasterBand(1).ReadAsArray()

        feedback.pushInfo(f'Raster read successfully: {in_dem.shape}')

        # Normalize 
        in_dem = (in_dem - in_dem.min()) / (in_dem.max() - in_dem.min())

        # Lineamentos de treinamento
        lineament_layer = self.parameterAsRasterLayer(
            parameters,
            self.LINEAMENT_ANNOTATION,
            context
        )

        if not lineament_layer:
            raise QgsProcessingException("Invalid input lineament layer.")

        if lineament_layer.bandCount() != 1:
            raise QgsProcessingException("Only for 1-band raster layers")
        
        # Open the file with GDAL
        lin_ds = gdal.Open(lineament_layer.dataProvider().dataSourceUri())
        in_sample = lin_ds.GetRasterBand(1).ReadAsArray()
        
        # inverter notação 0: fundo, 1: linhas
        in_sample = 1 - in_sample 

        feedback.pushInfo(f'Lineamento lido com sucesso: {in_dem.shape}')

        # Adicionando canal único aos shapes das imagens, por conformidade ao pytorch
        in_dem = in_dem[:,:,numpy.newaxis]
        in_sample = in_sample[:,:,numpy.newaxis]

        # Visualização de exemplos:
        # lib.view_random_sample(in_dem, in_sample, size=128)

        # device selection
        device = identify_device()
        feedback.pushInfo(f'Device auto-selected: {get_device_details(device)}')

        # Model parameters
        batch_size = self.parameterAsInt(parameters, self.BATCH_SIZE, context)
        tile_size = self.parameterAsInt(parameters, self.TILE_SIZE, context)
        learning_rate = self.parameterAsDouble(parameters, self.LEARNING_RATE, context)
        weight_decay = self.parameterAsDouble(parameters, self.WEIGHT_DECAY, context)
        num_epochs = self.parameterAsInt(parameters, self.NUM_EPOCHS, context)
        first_hidden_channels = self.parameterAsInt(parameters, self.FIRST_HIDDEN_CHANNELS, context)
        depth = self.parameterAsInt(parameters, self.DEPTH, context)
        model_name = self.parameterAsString(parameters, self.MODEL_NAME, context)
        output_path = Path(self.parameterAsString(parameters, self.OUTPUT_DIR, context))

        # Criar conjuntos de treinamento e validação
        train_dataloader = lib.load_examples(in_dem[:,:], in_sample[:,:], tile_size=tile_size, stride=8, batch_size=batch_size, shuffle=True)
        val_dataloader = lib.load_examples(in_dem[:,8:], in_sample[:,8:], tile_size=tile_size, stride=11, batch_size=batch_size, shuffle=True)

        feedback.pushInfo(f'Training dataset size: {len(train_dataloader.dataset)}')
        feedback.pushInfo(f'Vaidation dataset size: {len(val_dataloader.dataset)}')
        
        # Modelo U-Net
        model = lib.UNet(
            in_channels=1, 
            out_channels=1, 
            depth=depth, 
            first_hidden_channels=first_hidden_channels
        ).to(device.type)

        feedback.pushInfo(f'U-Net Model: {str(model)}')

        # Função de custo
        criterion = lib.DiceLoss()

        feedback.pushInfo(f'Cost Function: {str(criterion)}')

        # Otimizador
        optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)

        feedback.pushInfo(f'Optimizer: {str(optimizer)}')

        # Training
        metrics = lib.train_and_validate(
            model, 
            train_dataloader, 
            val_dataloader, 
            num_epochs, 
            criterion, 
            optimizer
        )

        lib.view_metrics(*metrics)

        # Escrevendo o arquivo de modelo
        out_model = output_path.joinpath(f"{model_name}.pth")
        torch.save(model, out_model)
            
        feedback.pushInfo(f'File saved successfully in: {out_model.as_posix()}')
        
        # Retorna o dicionário exigido pelo QGIS Processing
        return {self.OUTPUT_DIR: output_path}

    def createInstance(self):
        return GenerateModel()
